### ISSUE TITLE
UTableView show-total不起作用

### ISSUE THREAD

**Issue by whu-luojian** [vusion/proto-ui#67]
使用cloud-ui时使用UTableView组件时发现show-total属性不起作用，没有显示出条数，看了下代码（next分支），组合翻页组件使用prop totalItems来定义总条数，但是UTableView 组件并未传递该属性，其实有totalPage和pageSize属性可以直接计算总条数，不需额外定义prop totalItems

**Comment by rainfore** [comment]
感谢您反馈问题，我这边抓紧修复好发个版本。
请问您是哪位同事，我们方便联系~

**Comment by rainfore** [comment]
有totalPage和pageSize属性还是不能计算总条数。因为有余数的情况。

**Comment by rainfore** [comment]
已经发包
proto-ui.vusion@0.4.26
cloud-ui.vusion@0.4.13
